### ISSUE TITLE
Is this similar in scope to Emmet? 

### ISSUE THREAD

**Issue by jack-the-coder** [html-chp/chp#4]
[Emmet](https://www.emmet.io/) seems to do something like what you're writing here. Do you plan to write something similar?

**Comment by mbpscruise** [comment]
CHP is an HTML preprocessor, which converts clear & easy-to-use CHP syntax into HTML code. This project will include abbreviations to link popular external frameworks' and scripts' CDNs on the fly.

Check README,md for more details.

**Comment by mbpscruise** [comment]
Does this answer your question?

**Comment by jack-the-coder** [comment]
Thanks for the more detailed response! I understand much better now.
